sensor_id: salesforce # specify

sensor.source_code.main:
  class: github
  branch: salesforce
  path: https://github.com/cumulativedata/trel_contrib.git
sensor.main_executable: _code/sensors/salesforce/sfload.py
checked_out_files_to_use:
  - _code/sensors/salesforce/sflib.py
  - _code/sensors/destinations
manager_name: main
credentials.requested_name: default

dataset_class: salesforce.User # Other parameters can compute this
dataset_class_prefix: "salesforce."
instance_prefix: null # it is recommended you specify a value here, even when null.
instance_ts_precision: D # change based on frequency of drop
label: prod
repository: bq-us # specify destination repository

table_whitelist:
  - User
  - Account
  - Lead

# See schema management for details. As for now, this is only used as the attribute
# for the destination dataset and does not influence the schema of the destination.
# That is decided by querying the source table only.
schema_version: null

sleep_duration: 10 # Sleep for this long after each check

# It will generate a dataset for each timestamp in this set, subject to the precision.
cron_constraint: "0 0 * * *"

# How many seconds after the previous period is the next period considered ready?
# E.g., normally, with an hourly cadence, instance 20220101_04 will be ready to load
# as of 2022-01-01 05:00:00. With this parameter set to 60, it will be ready only
# as of 2022-01-01 05:00:30
delay_seconds: -86370

# Don't insert into the catalog, entries with
# intance_ts older than this many seconds.
max_instance_age_seconds:  86370

debug: [ "writes", "reads" ] # to debug the sensor add strings "writes" and "reads" into this list
